export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const GET_POSITIONS = "GET_POSITIONS";
export const GET_POSITIONS_SUCCESS = "GET_POSITIONS_SUCCESS";
export const GET_POSITIONS_FAILURE = "GET_POSITIONS_FAILURE";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_OFFSET_USERS= "GET_OFFSET_USERS";
export const GET_OFFSET_USERS_SUCCESS = "GET_OFFSET_USERS_SUCCESS";
export const GET_OFFSET_USERS_FAILURE = "GET_OFFSET_USERS_FAILURE";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILURE = "CREATE_NEW_USER_FAILURE";

export const GET_VALIDATE_SUCCESS = "GET_VALIDATE_SUCCESS";
